version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./data:/usr/src/app/data  # Монтируем папку data
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules